image: daimor/iris-community-gitpod:2020.3.0.200.0

tasks:
  - before: |
      waitISC.sh "$ISC_PACKAGE_INSTANCENAME" 60 "running"
    init: |
      cat << EOF | iris session $ISC_PACKAGE_INSTANCENAME -U %SYS
      do ##class(%SYSTEM.Process).CurrentDirectory("$PWD")
      do ##class(%SYSTEM.OBJ).Load("Installer.cls","ck")
      do ##class(App.Installer).setup(,3)
      halt
      EOF
    command:
      iris session iris -U IRISAPP
ports:
  - port: 52773
    onOpen: ignore
  - port: 1972
    onOpen: ignore
  - port: 51773
    onOpen: ignore 
